#!/usr/bin/env python3
"""
Generates Cowrie config files from config/identity.json.

Run from the project root:
    python config/cowrie_sync.py

Outputs to config/cowrie/ — copy into your Cowrie installation:
  config/cowrie/userdb.txt             -> <cowrie>/etc/userdb.txt
  config/cowrie/cowrie.cfg             -> merge into <cowrie>/etc/cowrie.cfg
  config/cowrie/honeyfs/               -> overlay onto <cowrie>/honeyfs/
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "cowrie")


def load_identity() -> dict:
    with open(os.path.join(HERE, "identity.json"), encoding="utf-8") as f:
        return json.load(f)


def write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path, HERE)}")


# Cowrie reads userdb passwords as regex patterns. A bare "*" or "!"
# can match any password (regex meta-character behavior varies by version),
# so accounts we want LOCKED need an unguessable literal string instead.
# 64 hex chars = 256 bits of entropy. Nobody is typing this.
_LOCKED_PW = "8a2f6c3b9e1d5470a4b7c8e6f2a3b9d1c5e0f4a7b8c2d3e6f9a1b4c5d8e2f036"


def gen_userdb(ident: dict) -> str:
    lines = []
    for u in ident["users"]:
        pw = u.get("ssh_password", "!")
        if pw in ("*", "!", ""):
            pw = _LOCKED_PW
        lines.append(f"{u['username']}:{u['uid']}:{pw}")
    return "\n".join(lines) + "\n"


def gen_cowrie_cfg(ident: dict) -> str:
    return (
        "# Generated by cowrie_sync.py — merge into <cowrie>/etc/cowrie.cfg\n"
        "[honeypot]\n"
        f"hostname = {ident['hostname']}\n"
        f"# kernel_version = {ident['kernel']}\n"
        "ssh_port = 2222\n"
        "telnet_port = 2223\n"
    )


def gen_etc_passwd(ident: dict) -> str:
    lines = [
        "root:x:0:0:root:/root:/bin/bash",
        "bin:x:1:1:bin:/bin:/sbin/nologin",
        "daemon:x:2:2:daemon:/sbin:/sbin/nologin",
        "mail:x:8:12:mail:/var/spool/mail:/sbin/nologin",
    ]
    for u in ident["users"]:
        if u["username"] == "nobody":
            lines.append(f"nobody:x:{u['uid']}:{u['uid']}:{u['fullname']}:/:/sbin/nologin")
        elif u["username"] != "admin":
            home = f"/home/{u['username']}"
            lines.append(f"{u['username']}:x:{u['uid']}:{u['uid']}:{u['fullname']}:{home}:{u['shell']}")
    return "\n".join(lines) + "\n"


def gen_etc_hostname(ident: dict) -> str:
    return ident["hostname"] + "\n"


def gen_redhat_release(ident: dict) -> str:
    return f"{ident['os']} release {ident['os_version']}\n"


def gen_proc_version(ident: dict) -> str:
    return (
        f"Linux version {ident['kernel']} (mockbuild@build-rh.corp.local) "
        "(gcc version 3.4.6 20060404 (Red Hat 3.4.6-9)) "
        "#1 SMP Tue May 22 12:45:17 EDT 2007\n"
    )


def gen_motd(ident: dict) -> str:
    return (
        "***********************************************************\n"
        f"*  {ident['hostname']} ({ident.get('fqdn', ident['hostname'])})\n"
        f"*  {ident.get('server_role', 'Internal server')}"
        f" -- {ident.get('department', 'IT')}\n"
        "*  Authorized use only. All activity is logged.\n"
        "***********************************************************\n"
        "\n"
    )


def gen_issue(ident: dict) -> str:
    # \r and \m are getty escapes (kernel release, machine arch).
    # Real RHEL /etc/issue contains them literally.
    return (
        f"{ident['os']} release {ident['os_version']}\n"
        "Kernel \\r on an \\m\n"
        "\n"
    )


def main() -> None:
    ident = load_identity()
    print(f"Syncing identity '{ident['hostname']}' to Cowrie config files...")

    write(os.path.join(OUT, "userdb.txt"),                          gen_userdb(ident))
    write(os.path.join(OUT, "cowrie.cfg"),                          gen_cowrie_cfg(ident))
    write(os.path.join(OUT, "honeyfs", "etc", "hostname"),          gen_etc_hostname(ident))
    write(os.path.join(OUT, "honeyfs", "etc", "redhat-release"),    gen_redhat_release(ident))
    write(os.path.join(OUT, "honeyfs", "etc", "passwd"),            gen_etc_passwd(ident))
    write(os.path.join(OUT, "honeyfs", "etc", "motd"),              gen_motd(ident))
    write(os.path.join(OUT, "honeyfs", "etc", "issue"),             gen_issue(ident))
    write(os.path.join(OUT, "honeyfs", "proc", "version"),          gen_proc_version(ident))

    print("\nDone. Copy into your Cowrie installation:")
    print("  config/cowrie/userdb.txt   ->  <cowrie>/etc/userdb.txt")
    print("  config/cowrie/cowrie.cfg   ->  merge into <cowrie>/etc/cowrie.cfg")
    print("  config/cowrie/honeyfs/     ->  overlay onto <cowrie>/honeyfs/")


if __name__ == "__main__":
    main()
